# 基本は github.com のレポジトリーを指定するだけ

# vimプラグイン管理用プラグイン
[[plugins]]
repo = 'Shougo/dein.vim'

# 非同期処理実現用プラグイン
[[plugins]]
repo = 'Shougo/vimproc.vim'

# ステータスバーカスタマイズ用プラグイン
[[plugins]]
repo    = 'vim-airline/vim-airline'
depends = ['vim-airline-themes']
# vim-airline用カラーテーマ
[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'osyo-manga/vim-precious'
depends = ['context_filetype.vim']

[[plugins]]
 repo = 'Shougo/context_filetype.vim'

# tomlファイルのシンタックスチェック用プラグイン
[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

#ディレクトリツリー表示用プラグイン
[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo =  'evidens/vim-twig'

[[plugins]]
repo =  'w0ng/vim-hybrid'

[[plugins]]
repo = 'jelera/vim-javascript-syntax'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'hail2u/vim-css3-syntax'

[[plugins]]
repo = 'othree/html5.vim'

[[plugins]]
repo = 'vim-scripts/jQuery'

[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

[[plugins]]
repo = 'Yggdroot/indentLine'

[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'rking/ag.vim'

[[plugins]]
repo = 'Shougo/neocomplete.vim'

[[plugins]]
repo = 'mattn/emmet-vim'

[[plugins]]
repo = 'ternjs/tern_for_vim'

[[plugins]]
repo = 'szw/vim-tags'

[[plugins]]
repo = 'majutsushi/tagbar'

[[plugins]]
repo = 'tpope/vim-markdown'

[[plugins]]
repo = 'kannokanno/previm'

[[plugins]]
repo = 'tyru/open-browser.vim'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'elzr/vim-json'

[[plugins]]
repo = 'romainl/Apprentice'
